# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define :archzfs do |zfs|
    zfs.vm.box = "archlinux/archlinux"
    zfs.ssh.forward_agent = true
    zfs.vm.synced_folder "..", "/vagrant"

    zfs.vm.provider "virtualbox" do |vb|
      disk_file = 'arch_zfs.vdi'
      vb.memory = "2048"
      vb.cpus = "2"
      unless File.exist?(disk_file)
        vb.customize ['createhd', '--filename', disk_file, '--size', 20 * 1024]
      end
       vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk_file]
#       vb.customize ["modifyvm", :id, "--firmware", "efi"]
    end

    zfs.vm.provision "shell", path: "./vagrant_provision.sh"
    # this does not seem to work
#    zfs.trigger.after :provision do |t|
#      t.name = "Reboot after provisioning"
#      t.run = { :inline => "vagrant reload" }
#    end
  end
end
